### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by amwww** [Tandhjulet/SkEssentials#2]
Stack Trace:
Paper 1.17.1 Server

[01:23:15 ERROR]: Error occurred while enabling SkEssentials v1.0.5 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/IChatBaseComponent
    at java.lang.Class.forName0(Native Method) ~[?:?]
    at java.lang.Class.forName(Class.java:467) ~[?:?]
    at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:117) ~[Skript.jar:?]
    at dk.tandhjulet.SkEssentials.onEnable(SkEssentials.java:47) ~[skessentials-1.0.5.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-411]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-411]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-411]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-411]
    at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-411]
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-411]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.IChatBaseComponent
    at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-411]
    at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-411]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
    ... 14 more

Then it disables itself

**Comment by Tandhjulet** [comment]
Hello, the plugin currently supports 1.8 only, and is no longer actively updated.
